apiVersion: v1
kind: Pod
metadata:
  name: bb
  namespace: default
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "infinity"]
    volumeMounts:
    - mountPath: /mnt/data  # El directorio donde se montará el PVC
      name: toletum-pvc  # El nombre del volumen (PVC)
  volumes:
  - name: toletum-pvc
    persistentVolumeClaim:
      claimName: toletum-pvc  # El nombre de tu PVC

