apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: toletum-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-static
  volumeMode: Filesystem
  volumeName: toletum-pv

