apiVersion: v1
kind: Service
metadata:
  name: mongo-0
spec:
  selector:
    app: mongo
    statefulset.kubernetes.io/pod-name: mongo-0
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30000  # Puedes cambiar esto si ya hay un puerto en uso
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-1
spec:
  selector:
    app: mongo
    statefulset.kubernetes.io/pod-name: mongo-1
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30001  # Puerto específico para mongo-1
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-2
spec:
  selector:
    app: mongo
    statefulset.kubernetes.io/pod-name: mongo-2
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30002  # Puerto específico para mongo-2
  type: NodePort
