apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: busyboxdaemons.toletum.org
spec:
  group: toletum.org
  names:
    kind: BusyboxDaemon
    plural: busyboxdaemons
    singular: busyboxdaemon
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
