apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: PLACEHOLDER_NAME
  labels:
    app: mongo-toletum-org-mongodb
spec:
  selector:
    matchLabels:
      app: mongo-toletum-org-mongodb
  template:
    metadata:
      labels:
        app: mongo-toletum-org-mongodb
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: mongo-toletum-org-mongodb
                operator: In
                values:
                - "true"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: mongo-toletum-org-mongodb
              topologyKey: kubernetes.io/hostname
      initContainers:
        - name: init-keyfile
          image: busybox
          command:
            - sh
            - -c
            - echo 'PLACEHOLDER_KEYFILE' > /data/db/keyfile && chmod 400 /data/db/keyfile && chown 999:999 -R /data/db
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      containers:
        - name: mongodb
          image: mongo:8.0
          args:
            - --replSet
            - rs0
            - --bind_ip_all
            - --auth
            - --keyFile=/data/db/keyfile
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          readinessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - db.adminCommand('ping')
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 5
          livenessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - db.adminCommand('ping')
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: mongo-data
          hostPath:
            path: /data/db
            type: DirectoryOrCreate

